"""`python -m fw_coordinator.contract`: writes contracts/openapi.yaml from the running API's models.

The file is generated, never hand-edited; a test fails when it is stale."""

from __future__ import annotations

from pathlib import Path

import yaml
from fastapi import FastAPI

from fw_coordinator.api import create_app
from fw_core.settings import CoordinatorSettings, load

CONTRACT = Path("contracts") / "openapi.yaml"
HEADER = "# GENERATED by `python -m fw_coordinator.contract` from fw_coordinator/schemas.py. Do not edit.\n"


def render(app: FastAPI) -> str:
    return HEADER + yaml.safe_dump(app.openapi(), sort_keys=True, allow_unicode=True, width=120)


def main() -> None:
    cfg = load(CoordinatorSettings)
    target = Path.cwd() / CONTRACT
    target.parent.mkdir(exist_ok=True)
    target.write_text(render(create_app(cfg)), encoding="utf-8", newline="\n")
    print(f"wrote {CONTRACT.as_posix()}")


if __name__ == "__main__":
    main()
